name: ad_qml_latent
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - black=22.3.0=pyhd8ed1ab_0
  - blas=1.0=mkl
  - ca-certificates=2022.5.18.1=ha878542_0
  - certifi=2022.5.18.1=py38h578d9bd_0
  - click=8.1.3=py38h578d9bd_0
  - dataclasses=0.8=pyhc8e2a94_3
  - h5py=3.6.0=py38ha0f2276_0
  - hdf5=1.10.6=hb1b8bf9_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_0
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=11.2.0=h1234567_0
  - libstdcxx-ng=11.2.0=h1234567_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - mypy_extensions=0.4.3=py38h578d9bd_5
  - ncurses=6.3=h7f8727e_2
  - numpy-base=1.21.5=py38hf524024_2
  - openssl=1.1.1o=h166bdaf_0
  - pathspec=0.9.0=pyhd8ed1ab_0
  - pip=21.2.4=py38h06a4308_0
  - platformdirs=2.5.1=pyhd8ed1ab_0
  - python=3.8.13=h12debd9_0
  - python_abi=3.8=2_cp38
  - readline=8.1.2=h7f8727e_1
  - setuptools=61.2.0=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.38.3=hc218d9a_0
  - tk=8.6.11=h1ccaba5_1
  - tomli=2.0.1=pyhd8ed1ab_0
  - typed-ast=1.4.3=py38h7f8727e_1
  - typing_extensions=4.2.0=pyha770c72_1
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.12=h7f8727e_2
  - pip:
    - cffi==1.15.0
    - charset-normalizer==2.0.12
    - cryptography==37.0.2
    - cycler==0.11.0
    - dill==0.3.5.1
    - fastdtw==0.3.4
    - fonttools==4.33.3
    - idna==3.3
    - joblib==1.1.0
    - kiwisolver==1.4.2
    - matplotlib==3.5.2
    - mpmath==1.2.1
    - ntlm-auth==1.5.0
    - numpy==1.22.4
    - packaging==21.3
    - pbr==5.9.0
    - pillow==9.1.1
    - ply==3.11
    - psutil==5.9.1
    - pycparser==2.21
    - pylatexenc==2.10
    - pyparsing==3.0.9
    - python-constraint==1.4.0
    - python-dateutil==2.8.2
    - qiskit==0.36.2
    - qiskit-aer==0.10.4
    - qiskit-ibmq-provider==0.19.1
    - qiskit-ignis==0.7.1
    - qiskit-machine-learning==0.4.0
    - qiskit-terra==0.20.2
    - requests==2.27.1
    - requests-ntlm==1.1.0
    - retworkx==0.11.0
    - scikit-learn==1.1.1
    - scipy==1.8.1
    - stevedore==3.5.0
    - symengine==0.9.2
    - sympy==1.10.1
    - threadpoolctl==3.1.0
    - tweedledum==1.1.1
    - urllib3==1.26.9
    - websocket-client==1.3.2
    - websockets==10.3
prefix: /work/vabelis/miniconda3/envs/ad_qml_latent
